import React from 'react'
import "./globals.css";
import { Navbar } from './Components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" !overflow-x-hidden">
      <Navbar/>
        {children}</body>
    </html>
  )
}
